
project_id = "umcociwvrzyqslkiejzv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.create-user]
verify_jwt = true

[functions.delete-auth-users]
verify_jwt = true

[functions.update-user-email]
verify_jwt = true

[functions.update-user-password]
verify_jwt = true

[functions.zatzet-sync]
verify_jwt = true
